[project]
name = "uptrader-test-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
]

[tool.basedpyright]
typeCheckingMode = "basic"
