# Generated by Django 5.2.1 on 2025-05-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item name')),
                ('menu_name', models.CharField(db_index=True, max_length=100, verbose_name='Menu name')),
                ('explicit_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Явный URL (напр., /about/)')),
                ('named_url', models.CharField(blank=True, max_length=100, null=True, verbose_name="Named URL (напр., 'article_detail')")),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_tree.menuitem', verbose_name='Parent Item')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
