# Generated by Django 5.2.1 on 2025-05-15 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu_name', 'parent__id', 'order', 'name'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Для сортировки пунктов на одном уровне.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='explicit_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Явный URL. Используется, если не указан named_url'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название пункта'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Named URL'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_tree.menuitem', verbose_name='Родительский пункт'),
        ),
    ]
